# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1483606975);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1483607095);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1483621069);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1483606855);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1483606735);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1483607215);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.dir", "/home/mathew/Desktop/HW");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1483606495);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 40);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1483702537127");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1483704349127");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1483620958028");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1483624558028");
user_pref("browser.search.countryCode", "IL");
user_pref("browser.search.region", "IL");
user_pref("browser.slowStartup.averageTime", 3949);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20161209094039");
user_pref("browser.startup.homepage_override.mstone", "50.1.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 2);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170106);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1483606557931");
user_pref("datareporting.sessions.current.activeTicks", 348);
user_pref("datareporting.sessions.current.firstPaint", 4311);
user_pref("datareporting.sessions.current.main", 125);
user_pref("datareporting.sessions.current.sessionRestored", 4017);
user_pref("datareporting.sessions.current.startTime", "1483606493914");
user_pref("datareporting.sessions.current.totalTime", 96417);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.512079");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"aushelper@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"50.1.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"50.1.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"firefox-hotfix@mozilla.org\":{\"version\":\"20160826.01\",\"type\":\"extension\",\"descriptor\":\"/home/mathew/.mozilla/firefox/31zclryc.default/extensions/firefox-hotfix@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318}");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:50.1.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1483606977);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "50.1.0");
user_pref("extensions.lastPlatformVersion", "50.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1481280493000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.5\",\"st\":1481280492000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1481280493000},\"aushelper@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1481280492000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"50.1.0\",\"st\":1481280492000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"50.1.0\",\"st\":1481280982000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"50.1.0\",\"st\":1481280981000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("idle.lastDailyNotification", 1483607389);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1483606560);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161209094039");
user_pref("media.gmp-manager.lastCheck", 1483606559);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1483607389);
user_pref("places.history.expiration.transient_current_max_pages", 69420);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1483471710);
user_pref("services.blocklist.clock_skew_seconds", 135385);
user_pref("services.blocklist.gfx.checked", 1483471710);
user_pref("services.blocklist.last_update_seconds", 1483471710);
user_pref("services.blocklist.plugins.checked", 1483471710);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1483607389);
user_pref("toolkit.startup.last_success", 1483606494);
user_pref("toolkit.telemetry.cachedClientID", "a75e1b70-e610-449c-855c-5f794152f81b");
user_pref("toolkit.telemetry.previousBuildID", "20161209094039");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
